In [2]:
import numpy as np
print(np.__version__)

2.4.2


In [1]:
# Numpy -> short for Numerical Python
# written in C++

In [ ]:
list=[1, 2, 3, 4]
print(list)
# if we multliply a list by 2, it will repeat the list twice
print(list*2)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


In [12]:
array=[1,2,3,4]
array=np.array(array)
array=np.array([1,2,3,4])
# we create numpy array by using np.array() function and passing a list as an argument

print(array)
print(type(array))   # we can check the type of the array by using type() function

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
print(array)
print(array*2)   # if we multliply a numpy array by 2, it will multiply each element of the array by 2

[1 2 3 4]
[2 4 6 8]


In [ ]:
# 0 dimension of the array
array0=np.array(10)
print(array0.ndim)   # 0 dimension array is called scalar

0


In [15]:
# 1 dimension of the array
array1=np.array([1,2,3,4])
print(array1)
print(array1.ndim)  # 1 dimension array is called vector

[1 2 3 4]
1


In [16]:
# 2 dimension of the array
array2=np.array([[1,2,3,4],[4,3,2,1]])
print(array2)
print(array2.ndim)  # 2 dimension array is called matrix

[[1 2 3 4]
 [4 3 2 1]]
2


In [23]:
#if array is 2d then all lists have to be homogenous or have same amount of nbrs.
array3=np.array([[[1,2,3],[4,5,6],[7,8,9]],
                #  [[1,2,3],[4,5,6],[7,8,9]],
                 [[1,2,3],[4,5,6],[7,8,9]] ])

print(array3)
print(array3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
