In [1]:
import numpy as np

In [3]:
#scaler arthemetic = it is the operation between a single number and an array.
array1=np.array([1,2,3,4])
print(array1+1)
print(array1-1)
print(array1*2)
print(array1/2)
print(array1**2)

[2 3 4 5]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [7]:
#vectorized math functions = it is the operation between two arrays of the same size.
array2=np.array([1,2,3,4.9])
print(np.sqrt(array2))
print(np.round(array2))
print(np.pi)

[1.         1.41421356 1.73205081 2.21359436]
[1. 2. 3. 5.]
3.141592653589793


In [9]:
radii=np.array([1,2,3,4])
print(np.pi*radii**2)

[ 3.14159265 12.56637061 28.27433388 50.26548246]


In [10]:
# element wise operations = it is the operation between two arrays of the same size.
array3=np.array([1,2,3])
array4=np.array([4,5,6])

print(array3+array4)
print(array3-array4)
print(array3*array4)
print(array3/array4)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# comparasion operators
scores=np.array([90,80,70,60,100])
# print(scores ==100)
print(scores >=70)
scores[scores <70]=0     #change the values that are less than 70 to 0
print(scores)

[ True  True  True False  True]
[ 90  80  70   0 100]
