In [1]:
import numpy as np

In [3]:
#scaler arthemetic = it is the operation between a single number and an array.
array1=np.array([1,2,3,4])
print(array1+1)
print(array1-1)
print(array1*2)
print(array1/2)
print(array1**2)

[2 3 4 5]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [7]:
#vectorized math functions = it is the operation between two arrays of the same size.
array2=np.array([1,2,3,4.9])
print(np.sqrt(array2))
print(np.round(array2))
print(np.pi)

[1.         1.41421356 1.73205081 2.21359436]
[1. 2. 3. 5.]
3.141592653589793


In [9]:
radii=np.array([1,2,3,4])
print(np.pi*radii**2)

[ 3.14159265 12.56637061 28.27433388 50.26548246]


In [10]:
# element wise operations = it is the operation between two arrays of the same size.
array3=np.array([1,2,3])
array4=np.array([4,5,6])

print(array3+array4)
print(array3-array4)
print(array3*array4)
print(array3/array4)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# comparasion operators
scores=np.array([90,80,70,60,100])
# print(scores ==100)
print(scores >=70)
scores[scores <70]=0     #change the values that are less than 70 to 0
print(scores)

[ True  True  True False  True]
[ 90  80  70   0 100]


In [30]:
#Broadsacting = it is operation btween arrays of different sizes. It is used to perform element wise operations between arrays of different sizes.
array5=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
array6=np.array([[1],[2],[3],[4]])
# print((array5.shape))
# print((array6.shape))
## we can only multiply the two arrays if the number of columns in the first array is equal to the number of rows in the second array. or any 1 of the arrays has only 1 row or 1 column.
print(array5*array6)


[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [39]:
# multipliaction table
array7=np.array([[1,2,3,4,5,6,7,8,9,10]])
array8=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array7.shape)
print(array8.shape)

print(array7*array8)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
